export const myOrders = [
  // {
  //   id: 1,
  //   orderItems:
  //     'Verusenaga Undalu,Nuvvula Undalu,Pappu Chekodi,Maramaralu Undalu',
  //   orderTotal: 1500,
  //   orderID: '#321567895',
  //   orderDate: '12/12/2022',
  //   orderTime: '11:32 am',
  //   orderStatus: 'Delivered',
  // },
  // {
  //   id: 2,
  //   orderItems:
  //     'Verusenaga Undalu,Nuvvula Undalu,Pappu Chekodi,Maramaralu Undalu',
  //   orderTotal: 3000,
  //   orderID: '#321561235',
  //   orderDate: '12/12/2022',
  //   orderTime: '11:32 am',
  //   orderStatus: 'In-Progress',
  // },
  // {
  //   id: 3,
  //   orderItems:
  //     'Verusenaga Undalu,Nuvvula Undalu,Pappu Chekodi,Maramaralu Undalu',
  //   orderTotal: 2500,
  //   orderID: '#321567532',
  //   orderDate: '12/12/2022',
  //   orderTime: '11:32 am',
  //   orderStatus: 'Delivered',
  // },

  {
    id: 1,
    orderTotal: 1000,
    deliveryFee: 100,
    orderStatus: 'Delivered',
    orderId: '#RJ_1234567',
    orderDate: '23/4/2022',
    orderTime: '11:32 am',
    paymentId: 12345678,
    paymentStatus: 'SUCCESS',
    deliveryAddress:
      '23b-7-21,Vasa vari street,opp.thrinath fashions,upstair DTDC courier service,RRPeta,Eluru',
    orderItems: [
      {
        id: 1,
        productCount: 1, // no of items in cart
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 19,
        productName: 'Verusenaga Undalu',
        productPrice: 300,
        quantity: 12,
        size: 'Small',
      },
      {
        id: 2,
        productCount: 2,
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 20,
        productName: 'Nuvvula Undalu',
        productPrice: 100,
        quantity: 12,
        size: 'Small',
      },
      {
        id: 3,
        productCount: 1,
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 21,
        productName: 'Pappu Chekodi',
        productPrice: 150,
        quantity: 12,
        size: 'Large',
      },
    ],
  },

  {
    id: 2,
    orderTotal: 2000,
    deliveryFee: 100,
    orderStatus: 'In-Progress',
    orderId: '#RJ_1234567',
    orderDate: '23/4/2022',
    orderTime: '11:32 am',
    paymentId: 12345678,
    paymentStatus: 'SUCCESS',
    deliveryAddress:
      '23b-7-21,Vasa vari street,opp.thrinath fashions,upstair DTDC courier service,RRPeta,Eluru',
    orderItems: [
      {
        id: 1,
        productCount: 1, // no of items in cart
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 19,
        productName: 'Pappu Chekodi',
        productPrice: 300,
        quantity: 12,
        size: 'Small',
      },
      {
        id: 2,
        productCount: 2,
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 20,
        productName: 'Nuvvula Undalu',
        productPrice: 100,
        quantity: 12,
        size: 'Small',
      },
      {
        id: 3,
        productCount: 1,
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 21,
        productName: 'Maramaralu Undalu',
        productPrice: 150,
        quantity: 12,
        size: 'Large',
      },
      {
        id: 4,
        productCount: 1,
        productDescription: 'In packet contains 12 pieces that contains 100g',
        productImage: 23,
        productName: 'Verusenaga Undalu',
        productPrice: 150,
        quantity: 10,
        size: 'Small',
      },
    ],
  },
];
